version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 528027818862.dkr.ecr.ap-northeast-3.amazonaws.com
  build:
    commands:
    - echo Build started on `date`
    - echo Building Java
    - cd authorization-microservice
    - mvn package -DskipTests
    - docker --version
    - echo Building the docker image..
    - docker build -t authorization-microservice .
    - echo Checking docker image authorization-microservice
    - docker images --filter reference=authorization-microservice
    - docker tag authorization-microservice 528027818862.dkr.ecr.ap-northeast-3.amazonaws.com/moviecrusier-auth-repo-2068215
    - echo Checking tag added before the docker image
    - docker images
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing docker image
    - docker push 528027818862.dkr.ecr.ap-northeast-3.amazonaws.com/moviecrusier-auth-repo-2068215:latest
    - echo Writting definition file
    - printf '[{"name":"auth-container-2068215","imageUri":"%s"}]' 528027818862.dkr.ecr.ap-northeast-3.amazonaws.com/moviecrusier-auth-repo-2068215 > imagedefinitions.json
artifacts:
  files:
  - authorization-microservice/imagedefinitions.json